spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.jaeung.dev/postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true


---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://130.162.136.116:3306
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true