spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.jaeung.dev/postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true