name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build
          build-root-directory: ./event
